version: "3.3"
services:
  mysqldocker:
    image: mysql:5.7
  
    environment:
      MYSQL_DATABASE: "my_store"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "sergio"
      # You can use whatever password you like
      MYSQL_PASSWORD: "sergiocastillo98"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "sergiocastillo98"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - ./my-db:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysqldocker
      PMA_USER: sergio
      PMA_PASSWORD: sergiocastillo98
    ports:
      - "8080:80"
