version: "3.3"
services:
  mysqldocker:
    image: mysql:5.7
  
    environment:
      MYSQL_DATABASE: "my_store"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "sergio"
      # You can use whatever password you like
      MYSQL_PASSWORD: "sergiocastillo98"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "sergiocastillo98"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - ./my-db:/var/lib/mysql
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=sergio
      - POSTGRES_PASSWORD=sergiocastillo98
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysqldocker
      PMA_USER: sergio
      PMA_PASSWORD: sergiocastillo98
    ports:
      - "8080:80"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
